### ISSUE TITLE
Ability to set upstream DNS servers?

### ISSUE THREAD

**Issue by accesstechnology-mike** [sreejithag/pi-hole-android-private-dns-docker#2]
I want to combine pi hole with cloudflare's family filter 1.1.1.3 - can I set an upstream DNS with this script?

**Comment by accesstechnology-mike** [comment]
Ok, I've seen the environment can be setup same as the normal pihole docker image, with DNS1 = 1.1.1.3 and DNS2 = 1.0.0.3

**Comment by sreejithag** [comment]
You can also add the upstream DNS servers from the front end after installation
sure environment variable works great 
Thanks
